<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <RuntimeIdentifiers>win-x64</RuntimeIdentifiers>
    <ApplicationIcon>Assets\zerocue.ico</ApplicationIcon>
    <PublishSingleFile>true</PublishSingleFile>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <BuiltInComInteropSupport>true</BuiltInComInteropSupport>
    <NuGetAudit>true</NuGetAudit>
    <NuGetAuditMode>all</NuGetAuditMode>
    <NuGetAuditLevel>high</NuGetAuditLevel>
    <WarningsAsErrors>$(WarningsAsErrors);NU1903;NU1904</WarningsAsErrors>
    <RestorePackagesWithLockFile>true</RestorePackagesWithLockFile>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" Version="11.3.18" />
    <PackageReference Include="Avalonia.Desktop" Version="11.3.18" />
    <PackageReference Include="Avalonia.Themes.Fluent" Version="11.3.18" />
    <PackageReference Include="Avalonia.Fonts.Inter" Version="11.3.18" />
    <PackageReference Include="LibUsbDotNet" Version="3.0.224" />
    <PackageReference Include="Material.Icons.Avalonia" Version="2.1.0" />
    <PackageReference Include="Nefarius.ViGEm.Client" Version="1.21.256" />
  </ItemGroup>

  <ItemGroup>
    <None Include="libusb-1.0.dll" CopyToOutputDirectory="PreserveNewest" />
    <None Include="scuf_mapping.json" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

  <ItemGroup>
    <AvaloniaResource Include="Assets\zerocue_logo_white.png" />
    <AvaloniaResource Include="Assets\gamepad-icons\Keyboard_Mouse\**\*.png" />
    <AvaloniaResource Include="Assets\gamepad-icons\XGamepad\**\*.png" />
    <AvaloniaResource Include="Assets\gamepad-icons\SGamepad\Default\T_S_Home.png" />
    <None Include="Assets\wdi-simple.exe" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

</Project>
