using System;
using System.Collections.Generic;
using Avalonia;

namespace ZeroCue.DataProbe.Services
{
    public static class LocalizationService
    {
        public const string English = "en";
        public const string Spanish = "es";

        private static string _currentLanguage = English;

        public static string CurrentLanguage => _currentLanguage;

        public static readonly IReadOnlyList<string> LanguageCodes = new[] { English, Spanish };

        private static readonly Dictionary<string, string> EnglishStrings = new()
        {
            ["LanguageEnglish"] = "English",
            ["LanguageSpanish"] = "Spanish",
            ["TrayOpen"] = "Open ZeroCue",
            ["TrayExit"] = "Exit ZeroCue",
            ["CloseDialogTitle"] = "Keep ZeroCue running?",
            ["CloseDialogDescription"] = "Minimize ZeroCue to the system tray to keep controller remapping active in the background, or exit the application completely.",
            ["MinimizeToTray"] = "Minimize to tray",
            ["ExitApplication"] = "Exit ZeroCue",
            ["RememberCloseSelection"] = "Remember my selection",
            ["CloseBehaviorSettings"] = "Closing",
            ["CloseBehavior"] = "Close behavior",
            ["CloseBehaviorDescription"] = "Choose what ZeroCue does when the confirmation dialog is disabled.",
            ["CloseBehaviorMinimize"] = "Minimize to tray",
            ["CloseBehaviorExit"] = "Exit application",
            ["AskBeforeClosing"] = "Ask before closing",
            ["AskBeforeClosingDescription"] = "Show the confirmation dialog when you press the close button.",
            ["NavMapping"] = "Mapping",
            ["NavProfiles"] = "Profiles",
            ["NavSettings"] = "Settings",
            ["TabMapping"] = "Mapping",
            ["TabTriggers"] = "Triggers",
            ["TabSticks"] = "Sticks",
            ["ControllerSettings"] = "Controller Settings",
            ["ActiveProfile"] = "Active Profile",
            ["New"] = "New",
            ["Battery"] = "Battery",
            ["BatteryInUse"] = "80% - In use",
            ["PowerMode"] = "Power Mode",
            ["EcoModeOn"] = "Eco Mode",
            ["EcoModeOff"] = "Eco Mode",
            ["EcoModeDescription"] = "Reduces brightness and disables vibration to save battery.",
            ["Vibration"] = "Vibration",
            ["Intensity"] = "Intensity:",
            ["TestRumble"] = "Test rumble",
            ["RgbLighting"] = "RGB Lighting",
            ["Standard"] = "Standard",
            ["Shift"] = "Shift",
            ["ShiftButton"] = "Shift Button",
            ["Unmapped"] = "Unmapped",
            ["EditShiftButton"] = "Edit Shift button",
            ["Change"] = "Change",
            ["Simple"] = "Simple",
            ["Advanced"] = "Advanced",
            ["ResetToDefault"] = "Reset to Default",
            ["SaveMapping"] = "Save Mapping",
            ["Cancel"] = "Cancel",
            ["Accept"] = "Accept",
            ["Processing"] = "Processing...",
            ["PowerShellProgress"] = "Watch the blue PowerShell console for progress...",
            ["Continue"] = "Continue",
            ["ResetMappingsTitle"] = "Reset mappings",
            ["ResetMappingsDescription"] = "Custom mappings, the Shift layer, Shift modifier, and all extra actions will be removed. The active profile will return to default values.",
            ["Reset"] = "Reset",
            ["SettingsTitle"] = "Settings",
            ["AppSettings"] = "App Settings",
            ["Language"] = "Language:",
            ["Theme"] = "Theme:",
            ["XboxIconVariant"] = "Xbox icon variant:",
            ["KeyboardMouseIconVariant"] = "Keyboard/mouse icon variant:",
            ["Disabled"] = "Disabled",
            ["Enabled"] = "Enabled",
            ["StartupSettings"] = "Startup",
            ["StartWithWindows"] = "Start with Windows",
            ["StartWithWindowsDescription"] = "Launch ZeroCue automatically when you sign in.",
            ["StartMinimized"] = "Start minimized",
            ["StartMinimizedDescription"] = "When ZeroCue opens from Windows startup, keep it minimized.",
            ["WinUsbDrivers"] = "WinUSB Drivers",
            ["UsbController"] = "Scuf USB Controller",
            ["RfReceiver"] = "Scuf Wireless Receiver",
            ["WinUsbUsageHelper"] = "Choose the driver for the way you want to use the controller: USB for cable, wireless for the Scuf receiver, or both if you want ZeroCue to handle both connection types. Once a WinUSB driver is installed for one connection type, iCUE will stop detecting the controller through that route.",
            ["WinUsbWhatIsTitle"] = "What are WinUSB drivers?",
            ["WinUsbWhatIsDescription"] = "WinUSB is a generic Windows driver that lets ZeroCue talk directly to the controller or receiver. ZeroCue installs or restores it with Administrator permissions, closes iCUE during the process, and only changes the connection type you choose here.",
            ["InstallUsbDriverDescription"] = "Use this when the controller is connected by USB.",
            ["InstallReceiverDriverDescription"] = "Use this when the controller is connected through the RF receiver.",
            ["InstallWinUsb"] = "Install WinUSB",
            ["RestoreDrivers"] = "Restore Drivers",
            ["ListPnpInstances"] = "Diagnostic: List PnP Instances",
            ["WirelessReceiverInstancesNotFound"] = "No wireless receiver PnP instances were found.",
            ["PowerShellLaunchFailed"] = "Could not launch PowerShell.",
            ["PowerShellExecutionErrorFormat"] = "{0}\nError:\n{1}",
            ["PowerShellExceptionFormat"] = "PowerShell error: {0}",
            ["KernelDriverCapabilityCheckFailedFormat"] = "[WARN] Could not check kernel-driver reattachment support: {0}",
            ["KernelDriverReattachFailedFormat"] = "[WARN] Could not reattach the kernel driver for USB interface {0}: {1}",
            ["ProfilesDashboard"] = "Profiles Dashboard",
            ["ProfilesSubtitle"] = "Manage and link your configuration profiles",
            ["None"] = "None",
            ["CreateNewProfile"] = "Create New Profile",
            ["ImportProfile"] = "Import Profile",
            ["ExportProfile"] = "Export Profile...",
            ["ProfileJsonFiles"] = "ZeroCue profiles",
            ["ImportProfileDialogTitle"] = "Import ZeroCue profile",
            ["ExportProfileDialogTitle"] = "Export ZeroCue profile",
            ["ImportProfileTitle"] = "Import profile",
            ["ImportedProfileDefaultName"] = "Imported Profile",
            ["ImportProfileDescription"] = "Confirm the name for this imported profile. Linked application paths are not imported.",
            ["ProfileImportInvalid"] = "This file is not a valid ZeroCue profile.",
            ["ProfileImportTooLarge"] = "This profile file is too large to import.",
            ["ProfileImportUnsupportedVersionFormat"] = "This profile uses format version {0}; this ZeroCue release supports version {1}.",
            ["ProfileImportReadFailedFormat"] = "The profile could not be read: {0}",
            ["ProfileImportSaveFailedFormat"] = "The profile could not be saved: {0}",
            ["ProfileExportSourceMissing"] = "The source profile no longer exists.",
            ["ProfileExportInvalid"] = "This profile contains invalid data and cannot be exported.",
            ["ProfileExportFailedFormat"] = "The profile could not be exported: {0}",
            ["ProfilePickerFailedFormat"] = "The file picker could not be opened: {0}",
            ["DeleteProfile"] = "Delete Profile",
            ["DuplicateProfile"] = "Duplicate",
            ["DuplicateProfileTitle"] = "Duplicate profile",
            ["DuplicateProfileDescriptionFormat"] = "Choose a name for the copy of '{0}'.",
            ["SetAsDefaultProfile"] = "Set as default",
            ["DefaultProfile"] = "Default profile",
            ["ProfileOptions"] = "Profile options",
            ["EditMapping"] = "Edit Mapping",
            ["ActivateProfile"] = "Activate",
            ["LinkExe"] = "Link app",
            ["ChangeLinkedExe"] = "Change app",
            ["AddLinkedExe"] = "Add app",
            ["RemoveLinkedExe"] = "Remove app links",
            ["RemoveAllLinkedExe"] = "Remove all",
            ["RemoveThisLinkedExe"] = "Remove this app",
            ["ManageLinkedApps"] = "Linked apps",
            ["LinkedAppCountFormat"] = "{0} linked",
            ["LinkedAppOverflowFormat"] = "+ {0} more",
            ["ManageLinkedAppsTitleFormat"] = "Linked apps for '{0}'",
            ["ManageLinkedAppsDescriptionFormat"] = "{0} app(s) activate this profile.",
            ["ActiveProfileBadge"] = "Active",
            ["ProfileLinkedApp"] = "Linked apps",
            ["ProfileNoLinkedAppHint"] = "No apps linked",
            ["CreateProfileTitle"] = "Create profile",
            ["CreateProfileDescription"] = "Choose a clear name for this controller configuration.",
            ["RenameProfileTitle"] = "Rename profile",
            ["RenameProfileDescriptionFormat"] = "Rename '{0}' without changing its mappings or linked app.",
            ["ProfileName"] = "Profile name",
            ["Save"] = "Save",
            ["ProfileNameRequired"] = "Enter a profile name.",
            ["ProfileNameInvalid"] = "The profile name contains invalid filename characters.",
            ["ProfileNameDuplicate"] = "A profile with that name already exists.",
            ["CannotDeleteLastProfile"] = "You need at least one profile.",
            ["DeleteProfileTitle"] = "Delete profile",
            ["DeleteProfileDescriptionFormat"] = "Delete '{0}' permanently? This removes its mappings and linked app.",
            ["LinkProfileTitle"] = "Link application",
            ["LinkProfileDescriptionFormat"] = "Link '{0}' to {1}. When that app is in the foreground, ZeroCue will activate this profile.",
            ["MultipleApplicationsFormat"] = "{0} applications",
            ["UnlinkProfileTitle"] = "Remove linked application",
            ["UnlinkProfileDescriptionFormat"] = "Remove the link between '{0}' and {1}?",
            ["ChooseExeTitle"] = "Choose application",
            ["ApplicationFiles"] = "Applications",
            ["NoActiveMappings"] = "No active mappings on this layer.",
            ["NoActiveMappingsHint"] = "Switch layers or configure actions from the other tabs.",
            ["DeleteAction"] = "Delete action",
            ["AddAction"] = "Add action",
            ["ChooseShiftButton"] = "Choose Shift button",
            ["Close"] = "Close",
            ["RemoveShiftButton"] = "Remove Shift button",
            ["RemoveShiftButtonTip"] = "Clears the current Shift modifier",
            ["TriggersTitle"] = "Triggers",
            ["LinearCurve"] = "Linear",
            ["ExponentialCurve"] = "Exponential",
            ["DynamicCurve"] = "Dynamic",
            ["AggressiveCurve"] = "Aggressive",
            ["CustomCurve"] = "Custom",
            ["LeftTrigger"] = "Left Trigger",
            ["RightTrigger"] = "Right Trigger",
            ["PhysicalInput"] = "Physical input",
            ["CurveOutput"] = "Curve output",
            ["ActiveCurve"] = "Active curve",
            ["LtOnCurve"] = "LT on curve",
            ["RtOnCurve"] = "RT on curve",
            ["InputFormat"] = "Input {0:0}%",
            ["DeltaFormat"] = "Delta {0:+0;-0;0}%",
            ["SticksTitle"] = "Sticks",
            ["PreciseCurve"] = "Precise",
            ["LeftStick"] = "Left Stick",
            ["RightStick"] = "Right Stick",
            ["Response"] = "Response",
            ["Input"] = "INPUT",
            ["Output"] = "OUTPUT",
            ["OutputSuffixFormat"] = "{0:0}% OUT",
            ["DeadzoneMin"] = "Deadzone min",
            ["DeadzoneMax"] = "Deadzone max",
            ["OriginalInput"] = "Original input",
            ["Original"] = "Original",
            ["AppliedOutput"] = "Applied output",
            ["XboxController"] = "Xbox Controller",
            ["Keyboard"] = "Keyboard",
            ["Mouse"] = "Mouse",
            ["Actions"] = "Actions",
            ["Macro"] = "Macro",
            ["Mapping"] = "Mapping",
            ["Action"] = "Action",
            ["AssignShiftModifier"] = "Shift modifier",
            ["ToggleEcoMode"] = "Toggle Eco Mode",
            ["LoadProfile"] = "Load Profile",
            ["SelectDestinationProfile"] = "Select profile",
            ["ProfileWhileHeld"] = "While pressed",
            ["MacroLibrary"] = "Macro Library",
            ["LoadSavedMacro"] = "Load saved macro...",
            ["SaveAs"] = "Save as...",
            ["SaveMacro"] = "Save Macro",
            ["MacroName"] = "Macro name:",
            ["MacroNameWatermark"] = "E.g. Combo 1",
            ["LoadMacro"] = "Load Macro",
            ["Load"] = "Load",
            ["Delete"] = "Delete",
            ["HoldDelayLabel"] = "Hold wait",
            ["DoubleTapDelayLabel"] = "Delay window",
            ["ActionsDisabledOnPressRelease"] = "Actions are disabled for On press and On release.",
            ["PrimaryProfileHeldConflict"] = "Action unavailable: the primary action already changes profile while pressed.",
            ["ProfileHeldPressReleaseUnavailable"] = "A profile cannot be held on On release because the button has already been released.",
            ["ProfileHeldSecondaryConflict"] = "A secondary action cannot hold another profile while the primary action already does it.",
            ["HoldProfileAlwaysWhileHeld"] = "On Hold, profile changes are always active only while you keep pressing.",
            ["RestoreOriginalMapping"] = "Restore original mapping",
            ["Unmap"] = "Unmap",
            ["UnmapTip"] = "Leaves this button without an action",
            ["PrimaryAction"] = "Primary action",
            ["DoubleTap"] = "Double tap",
            ["Hold"] = "Hold",
            ["PressStart"] = "On press",
            ["PressRelease"] = "On release",
            ["SinglePress"] = "Single press",
            ["NoModifier"] = "No modifier",
            ["Paddles"] = "Paddles",
            ["GKeys"] = "G-Keys",
            ["SideButtons"] = "Side Buttons",
            ["ActionButtons"] = "Action Buttons",
            ["TriggersAndBumpers"] = "Triggers and Bumpers",
            ["SticksAndDPad"] = "Sticks and D-Pad",
            ["System"] = "System",
            ["ShouldersAndTriggers"] = "Shoulders and triggers",
            ["DriverInstallTitle"] = "WinUSB Driver Installation",
            ["DriverInstallDescription"] = "Before continuing, keep the controller connected, either by USB cable or through the RF receiver. This helps Windows apply the driver to the correct device.\n\nZeroCue will close iCUE and run the driver installer with Administrator permissions. During the process you may hear the controller disconnect several times.\nDo you want to continue?",
            ["DriverRestoreTitle"] = "Original Driver Restoration",
            ["DriverRestoreDescription"] = "Before continuing, keep the controller connected, either by USB cable or through the RF receiver. This helps Windows restore the correct device driver.\n\nZeroCue will remove the WinUSB driver with Administrator permissions. You may need to unplug and reconnect the controller or restart the PC when it finishes.\nDo you want to continue?",
            ["ReceiverInstallTitle"] = "RF Receiver WinUSB Installation",
            ["ReceiverInstallDescription"] = "Before continuing, keep the controller connected, either by USB cable or through the RF receiver. This helps Windows apply the driver to the correct device.\n\nZeroCue will close iCUE and install WinUSB on the RF receiver with Administrator permissions.\nDo you want to continue?",
            ["ReceiverRestoreTitle"] = "RF Receiver Driver Restoration",
            ["ReceiverRestoreDescription"] = "Before continuing, keep the controller connected, either by USB cable or through the RF receiver. This helps Windows restore the correct receiver driver.\n\nZeroCue will remove the RF receiver WinUSB driver with Administrator permissions. Restarting the PC after this process is recommended for a clean reset.\nDo you want to continue?",
            ["PnpDiagnosticTitle"] = "Receiver PnP Diagnostic",
            ["QueryingInstances"] = "Querying instances...",
            ["ReceiverPnpInstancesTitle"] = "Receiver PnP Instances",
            ["ProcessingInstallDriver"] = "Installing WinUSB driver. Please accept the Administrator prompt...",
            ["ProcessingRestoreDriver"] = "Restoring original drivers. Please accept the Administrator prompt...",
            ["ProcessingInstallReceiver"] = "Installing WinUSB on the RF receiver. Please accept the Administrator prompt...",
            ["ProcessingRestoreReceiver"] = "Restoring original RF receiver drivers. Please accept the Administrator prompt...",
            ["OperationCompleted"] = "Operation Completed",
            ["DriverInstalledSuccess"] = "WinUSB driver installed successfully. Please unplug and reconnect the controller.",
            ["DriversRemovedSuccess"] = "Drivers removed successfully. Please unplug and reconnect the controller to use the default driver.",
            ["ReceiverDriverInstalledSuccess"] = "WinUSB driver installed successfully on the RF receiver. Please unplug and reconnect the receiver.",
            ["ReceiverDriversRemovedSuccess"] = "RF receiver drivers removed successfully. Please unplug and reconnect the receiver to use the default driver.",
            ["OperationFailed"] = "Operation Failed",
            ["OperationFailedDescription"] = "An error occurred or the process was cancelled. Check the logs for more details.",
            ["UnexpectedError"] = "Unexpected Error",
            ["UnexpectedErrorDescription"] = "An error occurred: {0}",
            ["ViGEmBusRequiredTitle"] = "ViGEmBus is required",
            ["ViGEmBusRequiredDescription"] = "ViGEmBus is not installed or is not working correctly. ZeroCue needs it to create the virtual Xbox 360 controller detected by games.\n\nInstall ViGEmBus and restart ZeroCue. Without it, ZeroCue may read the SCUF controller, but games and gamepad testers will not detect an Xbox controller.",
            ["TriggerCurveLinearDescription"] = "Output matches the physical reading.",
            ["TriggerCurveExponentialDescription"] = "Fine travel at the start and more power at the end.",
            ["TriggerCurveDynamicDescription"] = "Smooth compensation: keeps control and raises response.",
            ["TriggerCurveAggressiveDescription"] = "Fast output: 50% physical becomes about 80%.",
            ["StickCurveLinearDescription"] = "Output is proportional to input after deadzones.",
            ["StickCurvePreciseDescription"] = "Soft input around center for fine aiming.",
            ["StickCurveDynamicDescription"] = "Smooth center control with a more linear rise.",
            ["StickCurveAggressiveDescription"] = "Fast response: reaches high magnitudes sooner.",
            ["StickCurveCustomDescription"] = "Custom curve applied to magnitude after deadzones.",
            ["ButtonPaddleL4"] = "Paddle L4 (Inner Left)",
            ["ButtonPaddleL5"] = "Paddle L5 (Outer Left)",
            ["ButtonPaddleR4"] = "Paddle R4 (Inner Right)",
            ["ButtonPaddleR5"] = "Paddle R5 (Outer Right)",
            ["ButtonSaxL"] = "Left SAX",
            ["ButtonSaxR"] = "Right SAX",
            ["StatusWaitingController"] = "Waiting for controller",
            ["StatusConnectControllerHint"] = "Turn on the controller or connect it over USB.",
            ["StatusConnecting"] = "Connecting",
            ["StatusPreparingController"] = "Preparing controller.",
            ["StatusControllerConnected"] = "Controller connected",
            ["StatusControllerActive"] = "Input, remapping and configuration active.",
            ["StatusCannotConnect"] = "Could not connect",
            ["StatusDisconnectError"] = "Disconnect error",
            ["StatusWirelessSessionFailed"] = "Could not open the wireless WinUSB session.",
            ["MacroStopRecording"] = "Stop Recording",
            ["MacroStartRecording"] = "Start Recording",
            ["MacroClear"] = "Clear Macro",
            ["MacroRepeatWhileHeld"] = "Repeat while held",
            ["MacroRecordFixedDelay"] = "Record fixed delay",
            ["TriggerOutputScrollHint"] = "Scroll to change output percentage"
        };

        private static readonly Dictionary<string, string> SpanishStrings = new()
        {
            ["LanguageEnglish"] = "Ingles",
            ["LanguageSpanish"] = "Espanol",
            ["TrayOpen"] = "Abrir ZeroCue",
            ["TrayExit"] = "Salir de ZeroCue",
            ["CloseDialogTitle"] = "Quieres mantener ZeroCue activo?",
            ["CloseDialogDescription"] = "Minimiza ZeroCue a la bandeja del sistema para mantener el remapeo del mando activo en segundo plano, o sal por completo de la aplicacion.",
            ["MinimizeToTray"] = "Minimizar a la bandeja",
            ["ExitApplication"] = "Salir de ZeroCue",
            ["RememberCloseSelection"] = "Recordar mi seleccion",
            ["CloseBehaviorSettings"] = "Cierre",
            ["CloseBehavior"] = "Comportamiento al cerrar",
            ["CloseBehaviorDescription"] = "Elige que hara ZeroCue cuando el dialogo de confirmacion este desactivado.",
            ["CloseBehaviorMinimize"] = "Minimizar a la bandeja",
            ["CloseBehaviorExit"] = "Cerrar la aplicacion",
            ["AskBeforeClosing"] = "Preguntar antes de cerrar",
            ["AskBeforeClosingDescription"] = "Muestra el dialogo de confirmacion al pulsar el boton de cerrar.",
            ["NavMapping"] = "Mapeos",
            ["NavProfiles"] = "Perfiles",
            ["NavSettings"] = "Ajustes",
            ["TabMapping"] = "Mapeos",
            ["TabTriggers"] = "Gatillos",
            ["TabSticks"] = "Sticks",
            ["ControllerSettings"] = "Ajustes del mando",
            ["ActiveProfile"] = "Perfil activo",
            ["New"] = "Nuevo",
            ["Battery"] = "Bateria",
            ["BatteryInUse"] = "80% - En uso",
            ["PowerMode"] = "Modo de energia",
            ["EcoModeOn"] = "Eco Mode",
            ["EcoModeOff"] = "Eco Mode",
            ["EcoModeDescription"] = "Reduce el brillo y desactiva la vibracion para ahorrar bateria.",
            ["Vibration"] = "Vibracion",
            ["Intensity"] = "Intensidad:",
            ["TestRumble"] = "Probar vibracion",
            ["RgbLighting"] = "Iluminacion RGB",
            ["Standard"] = "Estandar",
            ["Shift"] = "Shift",
            ["ShiftButton"] = "Boton Shift",
            ["Unmapped"] = "Sin mapeo",
            ["EditShiftButton"] = "Editar boton Shift",
            ["Change"] = "Cambiar",
            ["Simple"] = "Simple",
            ["Advanced"] = "Avanzado",
            ["ResetToDefault"] = "Restablecer valores",
            ["SaveMapping"] = "Guardar mapeo",
            ["Cancel"] = "Cancelar",
            ["Accept"] = "Aceptar",
            ["Processing"] = "Procesando...",
            ["PowerShellProgress"] = "Mira la consola azul de PowerShell para ver el progreso...",
            ["Continue"] = "Continuar",
            ["ResetMappingsTitle"] = "Restablecer mapeos",
            ["ResetMappingsDescription"] = "Se eliminaran los mapeos personalizados, la capa Shift, el modificador Shift y todas las acciones extra. El perfil activo quedara con los valores predeterminados.",
            ["Reset"] = "Restablecer",
            ["SettingsTitle"] = "Ajustes",
            ["AppSettings"] = "Ajustes de la aplicacion",
            ["Language"] = "Idioma:",
            ["Theme"] = "Tema:",
            ["XboxIconVariant"] = "Variante iconos Xbox:",
            ["KeyboardMouseIconVariant"] = "Variante iconos teclado/raton:",
            ["Disabled"] = "Desactivado",
            ["Enabled"] = "Activado",
            ["StartupSettings"] = "Inicio",
            ["StartWithWindows"] = "Iniciar con Windows",
            ["StartWithWindowsDescription"] = "Abre ZeroCue automaticamente al iniciar sesion.",
            ["StartMinimized"] = "Iniciar minimizado",
            ["StartMinimizedDescription"] = "Cuando ZeroCue se abra con Windows, mantenlo minimizado.",
            ["WinUsbDrivers"] = "Drivers WinUSB",
            ["UsbController"] = "Scuf USB Controller",
            ["RfReceiver"] = "Scuf Wireless Receiver",
            ["WinUsbUsageHelper"] = "Elige el driver segun como quieras usar el mando: USB para cable, wireless para el receptor Scuf, o ambos si quieres que ZeroCue controle los dos tipos de conexion. Cuando instales WinUSB para una conexion, iCUE dejara de detectar el mando por esa via.",
            ["WinUsbWhatIsTitle"] = "Que son los drivers WinUSB?",
            ["WinUsbWhatIsDescription"] = "WinUSB es un driver generico de Windows que permite a ZeroCue comunicarse directamente con el mando o el receptor. ZeroCue lo instala o lo restaura con permisos de Administrador, cierra iCUE durante el proceso y solo cambia el tipo de conexion que elijas aqui.",
            ["InstallUsbDriverDescription"] = "Usalo cuando el mando este conectado por cable USB.",
            ["InstallReceiverDriverDescription"] = "Usalo cuando el mando este conectado a traves del receptor RF.",
            ["InstallWinUsb"] = "Instalar WinUSB",
            ["RestoreDrivers"] = "Restaurar drivers",
            ["ListPnpInstances"] = "Diagnostico: listar instancias PnP",
            ["WirelessReceiverInstancesNotFound"] = "No se encontraron instancias PnP del receptor inalambrico.",
            ["PowerShellLaunchFailed"] = "No se pudo iniciar PowerShell.",
            ["PowerShellExecutionErrorFormat"] = "{0}\nError:\n{1}",
            ["PowerShellExceptionFormat"] = "Error de PowerShell: {0}",
            ["KernelDriverCapabilityCheckFailedFormat"] = "[AVISO] No se pudo comprobar si el driver del kernel puede reengancharse: {0}",
            ["KernelDriverReattachFailedFormat"] = "[AVISO] No se pudo reenganchar el driver del kernel para la interfaz USB {0}: {1}",
            ["ProfilesDashboard"] = "Panel de perfiles",
            ["ProfilesSubtitle"] = "Administra y vincula tus perfiles de configuracion",
            ["None"] = "Ninguna",
            ["CreateNewProfile"] = "Crear nuevo perfil",
            ["ImportProfile"] = "Importar perfil",
            ["ExportProfile"] = "Exportar perfil...",
            ["ProfileJsonFiles"] = "Perfiles de ZeroCue",
            ["ImportProfileDialogTitle"] = "Importar perfil de ZeroCue",
            ["ExportProfileDialogTitle"] = "Exportar perfil de ZeroCue",
            ["ImportProfileTitle"] = "Importar perfil",
            ["ImportedProfileDefaultName"] = "Perfil importado",
            ["ImportProfileDescription"] = "Confirma el nombre del perfil importado. Las rutas de aplicaciones vinculadas no se importan.",
            ["ProfileImportInvalid"] = "El archivo no es un perfil de ZeroCue valido.",
            ["ProfileImportTooLarge"] = "El archivo de perfil es demasiado grande para importarlo.",
            ["ProfileImportUnsupportedVersionFormat"] = "El perfil usa la version de formato {0}; esta version de ZeroCue admite la {1}.",
            ["ProfileImportReadFailedFormat"] = "No se pudo leer el perfil: {0}",
            ["ProfileImportSaveFailedFormat"] = "No se pudo guardar el perfil: {0}",
            ["ProfileExportSourceMissing"] = "El perfil de origen ya no existe.",
            ["ProfileExportInvalid"] = "El perfil contiene datos no validos y no se puede exportar.",
            ["ProfileExportFailedFormat"] = "No se pudo exportar el perfil: {0}",
            ["ProfilePickerFailedFormat"] = "No se pudo abrir el selector de archivos: {0}",
            ["DeleteProfile"] = "Eliminar perfil",
            ["DuplicateProfile"] = "Duplicar",
            ["DuplicateProfileTitle"] = "Duplicar perfil",
            ["DuplicateProfileDescriptionFormat"] = "Elige un nombre para la copia de '{0}'.",
            ["SetAsDefaultProfile"] = "Establecer por defecto",
            ["DefaultProfile"] = "Perfil por defecto",
            ["ProfileOptions"] = "Opciones del perfil",
            ["EditMapping"] = "Editar mapeo",
            ["ActivateProfile"] = "Activar",
            ["LinkExe"] = "Vincular app",
            ["ChangeLinkedExe"] = "Cambiar app",
            ["AddLinkedExe"] = "Anadir app",
            ["RemoveLinkedExe"] = "Quitar vinculos de apps",
            ["RemoveAllLinkedExe"] = "Quitar todo",
            ["RemoveThisLinkedExe"] = "Quitar esta app",
            ["ManageLinkedApps"] = "Apps vinculadas",
            ["LinkedAppCountFormat"] = "{0} vinculadas",
            ["LinkedAppOverflowFormat"] = "+ {0} mas",
            ["ManageLinkedAppsTitleFormat"] = "Apps vinculadas a '{0}'",
            ["ManageLinkedAppsDescriptionFormat"] = "{0} app(s) activan este perfil.",
            ["ActiveProfileBadge"] = "Activo",
            ["ProfileLinkedApp"] = "Aplicaciones vinculadas",
            ["ProfileNoLinkedAppHint"] = "Sin aplicaciones vinculadas",
            ["CreateProfileTitle"] = "Crear perfil",
            ["CreateProfileDescription"] = "Elige un nombre claro para esta configuracion del mando.",
            ["RenameProfileTitle"] = "Renombrar perfil",
            ["RenameProfileDescriptionFormat"] = "Renombra '{0}' sin cambiar sus mapeos ni su aplicacion vinculada.",
            ["ProfileName"] = "Nombre del perfil",
            ["Save"] = "Guardar",
            ["ProfileNameRequired"] = "Introduce un nombre para el perfil.",
            ["ProfileNameInvalid"] = "El nombre del perfil contiene caracteres no validos para archivos.",
            ["ProfileNameDuplicate"] = "Ya existe un perfil con ese nombre.",
            ["CannotDeleteLastProfile"] = "Necesitas al menos un perfil.",
            ["DeleteProfileTitle"] = "Eliminar perfil",
            ["DeleteProfileDescriptionFormat"] = "Eliminar '{0}' de forma permanente? Se borraran sus mapeos y su aplicacion vinculada.",
            ["LinkProfileTitle"] = "Vincular aplicacion",
            ["LinkProfileDescriptionFormat"] = "Vincular '{0}' a {1}. Cuando esa aplicacion este en primer plano, ZeroCue activara este perfil.",
            ["MultipleApplicationsFormat"] = "{0} aplicaciones",
            ["UnlinkProfileTitle"] = "Quitar aplicacion vinculada",
            ["UnlinkProfileDescriptionFormat"] = "Quitar el vinculo entre '{0}' y {1}?",
            ["ChooseExeTitle"] = "Elegir aplicacion",
            ["ApplicationFiles"] = "Aplicaciones",
            ["NoActiveMappings"] = "No hay mapeos activos en esta capa.",
            ["NoActiveMappingsHint"] = "Cambia de capa o configura acciones desde las otras pestanas.",
            ["DeleteAction"] = "Eliminar accion",
            ["AddAction"] = "Anadir accion",
            ["ChooseShiftButton"] = "Elegir boton Shift",
            ["Close"] = "Cerrar",
            ["RemoveShiftButton"] = "Eliminar boton Shift",
            ["RemoveShiftButtonTip"] = "Quita el modificador Shift actual",
            ["TriggersTitle"] = "Gatillos",
            ["LinearCurve"] = "Lineal",
            ["ExponentialCurve"] = "Exponencial",
            ["DynamicCurve"] = "Dinamica",
            ["AggressiveCurve"] = "Agresiva",
            ["CustomCurve"] = "Custom",
            ["LeftTrigger"] = "Gatillo izquierdo",
            ["RightTrigger"] = "Gatillo derecho",
            ["PhysicalInput"] = "Entrada fisica",
            ["CurveOutput"] = "Salida de curva",
            ["ActiveCurve"] = "Curva activa",
            ["LtOnCurve"] = "LT en curva",
            ["RtOnCurve"] = "RT en curva",
            ["InputFormat"] = "Entrada {0:0}%",
            ["DeltaFormat"] = "Delta {0:+0;-0;0}%",
            ["SticksTitle"] = "Sticks",
            ["PreciseCurve"] = "Precisa",
            ["LeftStick"] = "Stick izquierdo",
            ["RightStick"] = "Stick derecho",
            ["Response"] = "Respuesta",
            ["Input"] = "ENTRADA",
            ["Output"] = "SALIDA",
            ["OutputSuffixFormat"] = "{0:0}% SALIDA",
            ["DeadzoneMin"] = "Deadzone min",
            ["DeadzoneMax"] = "Deadzone max",
            ["OriginalInput"] = "Input original",
            ["Original"] = "Original",
            ["AppliedOutput"] = "Output aplicado",
            ["XboxController"] = "Mando Xbox",
            ["Keyboard"] = "Teclado",
            ["Mouse"] = "Raton",
            ["Actions"] = "Acciones",
            ["Macro"] = "Macro",
            ["Mapping"] = "Mapeando",
            ["Action"] = "Accion",
            ["AssignShiftModifier"] = "Modificador shift",
            ["ToggleEcoMode"] = "Alternar Eco Mode",
            ["LoadProfile"] = "Cargar perfil",
            ["SelectDestinationProfile"] = "Seleccionar perfil",
            ["ProfileWhileHeld"] = "Mientras se pulsa",
            ["MacroLibrary"] = "Libreria de macros",
            ["LoadSavedMacro"] = "Cargar macro guardada...",
            ["SaveAs"] = "Guardar como...",
            ["SaveMacro"] = "Guardar macro",
            ["MacroName"] = "Nombre de la macro:",
            ["MacroNameWatermark"] = "Ej. Combo 1",
            ["LoadMacro"] = "Cargar macro",
            ["Load"] = "Cargar",
            ["Delete"] = "Borrar",
            ["HoldDelayLabel"] = "Espera Hold",
            ["DoubleTapDelayLabel"] = "Ventana delay",
            ["ActionsDisabledOnPressRelease"] = "Las acciones estan deshabilitadas en Al pulsar y Al soltar.",
            ["PrimaryProfileHeldConflict"] = "Accion no disponible: la accion principal ya cambia de perfil mientras se pulsa.",
            ["ProfileHeldPressReleaseUnavailable"] = "No se puede mantener un perfil en Al soltar porque el boton ya se ha soltado.",
            ["ProfileHeldSecondaryConflict"] = "No se puede mantener otro perfil en una accion secundaria cuando la primaria ya lo hace.",
            ["HoldProfileAlwaysWhileHeld"] = "En Hold, el cambio de perfil siempre se mantiene solo mientras sigues pulsando.",
            ["RestoreOriginalMapping"] = "Restaura el mapeo original",
            ["Unmap"] = "Desmapear",
            ["UnmapTip"] = "Deja este boton sin accion",
            ["PrimaryAction"] = "Accion principal",
            ["DoubleTap"] = "Doble pulsacion",
            ["Hold"] = "Mantener",
            ["PressStart"] = "Al pulsar",
            ["PressRelease"] = "Al soltar",
            ["SinglePress"] = "Pulsacion simple",
            ["NoModifier"] = "Sin modificador",
            ["Paddles"] = "Palancas",
            ["GKeys"] = "Teclas G",
            ["SideButtons"] = "Botones laterales",
            ["ActionButtons"] = "Botones de accion",
            ["TriggersAndBumpers"] = "Gatillos y bumpers",
            ["SticksAndDPad"] = "Sticks y D-Pad",
            ["System"] = "Sistema",
            ["ShouldersAndTriggers"] = "Hombros y gatillos",
            ["DriverInstallTitle"] = "Instalacion de drivers WinUSB",
            ["DriverInstallDescription"] = "Antes de continuar, manten el mando conectado, ya sea por USB o por RF. Asi Windows puede aplicar el driver al dispositivo correcto.\n\nZeroCue cerrara iCUE y ejecutara el instalador con permisos de Administrador. Durante el proceso puedes escuchar al mando desconectarse varias veces.\nDeseas continuar?",
            ["DriverRestoreTitle"] = "Restauracion de drivers originales",
            ["DriverRestoreDescription"] = "Antes de continuar, manten el mando conectado, ya sea por USB o por RF. Asi Windows puede restaurar el driver del dispositivo correcto.\n\nZeroCue eliminara el driver WinUSB con permisos de Administrador. Es probable que necesites desconectar y volver a conectar el mando o reiniciar el PC al terminar.\nDeseas continuar?",
            ["ReceiverInstallTitle"] = "Instalacion WinUSB del receptor RF",
            ["ReceiverInstallDescription"] = "Antes de continuar, manten el mando conectado, ya sea por USB o por RF. Asi Windows puede aplicar el driver al dispositivo correcto.\n\nZeroCue cerrara iCUE e instalara WinUSB en el receptor RF con permisos de Administrador.\nQuieres continuar?",
            ["ReceiverRestoreTitle"] = "Restauracion de drivers del receptor RF",
            ["ReceiverRestoreDescription"] = "Antes de continuar, manten el mando conectado, ya sea por USB o por RF. Asi Windows puede restaurar el driver del receptor correcto.\n\nZeroCue eliminara el driver WinUSB del receptor RF con permisos de Administrador. Es recomendable reiniciar el PC al terminar para un restablecimiento limpio.\nQuieres continuar?",
            ["PnpDiagnosticTitle"] = "Diagnostico PnP del receptor",
            ["QueryingInstances"] = "Consultando instancias...",
            ["ReceiverPnpInstancesTitle"] = "Instancias PnP del receptor",
            ["ProcessingInstallDriver"] = "Instalando driver WinUSB. Por favor, acepta los permisos de Administrador...",
            ["ProcessingRestoreDriver"] = "Restaurando drivers originales. Por favor, acepta los permisos de Administrador...",
            ["ProcessingInstallReceiver"] = "Instalando WinUSB en el receptor RF. Por favor, acepta los permisos de Administrador...",
            ["ProcessingRestoreReceiver"] = "Restaurando drivers originales del receptor RF. Por favor, acepta los permisos de Administrador...",
            ["OperationCompleted"] = "Operacion completada",
            ["DriverInstalledSuccess"] = "Driver WinUSB instalado con exito. Por favor, desconecta y reconecta el mando.",
            ["DriversRemovedSuccess"] = "Drivers eliminados correctamente. Por favor, desconecta y reconecta el mando para usar el driver por defecto.",
            ["ReceiverDriverInstalledSuccess"] = "Driver WinUSB instalado con exito en el receptor RF. Por favor, desconecta y reconecta el receptor.",
            ["ReceiverDriversRemovedSuccess"] = "Drivers del receptor RF eliminados correctamente. Por favor, desconecta y reconecta el receptor para usar el driver por defecto.",
            ["OperationFailed"] = "Operacion fallida",
            ["OperationFailedDescription"] = "Ocurrio un error o el proceso fue cancelado. Revisa los logs para mas detalles.",
            ["UnexpectedError"] = "Error inesperado",
            ["UnexpectedErrorDescription"] = "Se produjo un error: {0}",
            ["ViGEmBusRequiredTitle"] = "ViGEmBus es necesario",
            ["ViGEmBusRequiredDescription"] = "ViGEmBus no esta instalado o no funciona correctamente. ZeroCue lo necesita para crear el mando virtual Xbox 360 que detectan los juegos.\n\nInstala ViGEmBus y reinicia ZeroCue. Sin el, ZeroCue puede leer el mando SCUF, pero los juegos y los gamepad testers no detectaran un mando Xbox.",
            ["TriggerCurveLinearDescription"] = "Salida identica a la lectura fisica.",
            ["TriggerCurveExponentialDescription"] = "Recorrido fino al inicio y mas potencia al final.",
            ["TriggerCurveDynamicDescription"] = "Compensa suavemente: mantiene control y sube la respuesta.",
            ["TriggerCurveAggressiveDescription"] = "Salida rapida: 50% fisico se convierte en aprox. 80%.",
            ["StickCurveLinearDescription"] = "Salida proporcional a la entrada despues de deadzones.",
            ["StickCurvePreciseDescription"] = "Entrada suave alrededor del centro para apuntado fino.",
            ["StickCurveDynamicDescription"] = "Control suave en centro, ahora con una subida mas lineal.",
            ["StickCurveAggressiveDescription"] = "Respuesta rapida: llega antes a magnitudes altas.",
            ["StickCurveCustomDescription"] = "Curva personalizada aplicada a la magnitud tras deadzones.",
            ["ButtonPaddleL4"] = "Palanca L4 (int izq)",
            ["ButtonPaddleL5"] = "Palanca L5 (ext izq)",
            ["ButtonPaddleR4"] = "Palanca R4 (int der)",
            ["ButtonPaddleR5"] = "Palanca R5 (ext der)",
            ["ButtonSaxL"] = "SAX izquierdo",
            ["ButtonSaxR"] = "SAX derecho",
            ["StatusWaitingController"] = "Esperando mando",
            ["StatusConnectControllerHint"] = "Enciende el mando o conectalo por USB.",
            ["StatusConnecting"] = "Conectando",
            ["StatusPreparingController"] = "Preparando el mando.",
            ["StatusControllerConnected"] = "Mando conectado",
            ["StatusControllerActive"] = "Entrada, remapeo y configuracion activos.",
            ["StatusCannotConnect"] = "No se pudo conectar",
            ["StatusDisconnectError"] = "Error al desconectar",
            ["StatusWirelessSessionFailed"] = "No se pudo abrir la sesion wireless WinUSB.",
            ["MacroStopRecording"] = "Parar grabación",
            ["MacroStartRecording"] = "Iniciar grabación",
            ["MacroClear"] = "Limpiar macro",
            ["MacroRepeatWhileHeld"] = "Repetir mientras se mantiene pulsado",
            ["MacroRecordFixedDelay"] = "Grabar con delay fijo",
            ["TriggerOutputScrollHint"] = "Desplaza para cambiar el porcentaje de salida"
        };

        public static void SetLanguage(string? languageCode)
        {
            _currentLanguage = NormalizeLanguageCode(languageCode);
            ApplyResources();
        }

        public static string NormalizeLanguageCode(string? languageCode)
        {
            return string.Equals(languageCode, Spanish, StringComparison.OrdinalIgnoreCase)
                ? Spanish
                : English;
        }

        public static int GetLanguageIndex(string? languageCode)
        {
            return NormalizeLanguageCode(languageCode) == Spanish ? 1 : 0;
        }

        public static string GetLanguageCode(int index)
        {
            return index == 1 ? Spanish : English;
        }

        public static string Get(string key)
        {
            var strings = _currentLanguage == Spanish ? SpanishStrings : EnglishStrings;
            if (strings.TryGetValue(key, out var value))
            {
                return value;
            }

            return EnglishStrings.TryGetValue(key, out var fallback) ? fallback : key;
        }

        private static void ApplyResources()
        {
            if (Application.Current == null)
            {
                return;
            }

            foreach (var key in EnglishStrings.Keys)
            {
                Application.Current.Resources[key] = Get(key);
            }
        }
    }
}
